news_scraper/urls.py
from django.urls import path
from . import views

app_name = "news"

urlpatterns = [
    path('', views.NewspapersIndexView.as_view(), name='index'),
    path("<int:pk>/", views.newspaper, name='newspaper')
]

personal/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('news/',include('news_scraper.urls')),
    path('admin/', admin.site.urls),
]

news_scraper/models.py
from django.db import models

# Create your models here.

class Newspaper(models.Model):
    """
    # Newspaper
    A newspaper class all articles belonging to this newspaper
    point to

    ## Fields:
    newspaper_name: A CharField of max_length=50
    """

    newspaper_name = models.CharField(max_length=50)
    
    def __str__(self) -> str:
        return self.newspaper_name

class Author(models.Model):

    name = models.CharField(max_length=100,default=None)

    def __str__(self) -> str:
        return self.name

class Article(models.Model):
    """
    # Article
    An article class with various relevant info

    ## Fields:
    - newspaper: a Newspaper instance
    - headline: a CharField of max_length=200
    - author: an Author instance
    - category: a Charfield of max_length=50
    - pub_day: a DateField
    - link: an URLField
    """
    newspaper = models.ForeignKey(Newspaper,on_delete=models.CASCADE)
    headline = models.CharField(max_length=200)
    author = models.ForeignKey(Author,on_delete=models.CASCADE,null=True)
    category = models.CharField(max_length=50)
    pub_day = models.DateField()
    link = models.URLField()

    def __str__(self) -> str:
        return self.headline

news_scraper/views.py
from django.shortcuts import render
from django.views import generic
from .models import Newspaper
from django.shortcuts import render,get_object_or_404
# Create your views here.

class NewspapersIndexView(generic.ListView):
    template_name="news/newspapers_index.html"
    context_object_name = 'newspaper_list'

    def get_queryset(self):
        return Newspaper.objects.all()
    

def newspaper(request, pk):
    template_name="news/newspaper.html"
    newspaper = get_object_or_404(Newspaper,id=pk)
    all_news = newspaper.article_set.all()

    #Get all sections and the 6 most recent news per section
    sections = all_news.values("category").distinct()
    sections = [cat["category"] for cat in sections]
    filtered_news = dict() 
    for section in sections:
        filtered_news[section] = all_news.filter(category=section).order_by('-pub_day','-id')[0:6]
    return render(request,template_name,{
        'newspaper':newspaper,
        'filtered_news':filtered_news
    })

news_scraper/templates/news/newspaper.html
<h1>Resúmen de {{newspaper.newspaper_name}}</h1>
<a href="{% url 'news:index' %}">Volver al índice de diarios</a>
<hr>
{% for section,articles in filtered_news.items %}
    <h3><em>{{section}}</em></h3>
    <ul>
        {% for article in articles %}
            <li><p>
            <a href={{article.link}}><strong>{{article.headline}}</strong></a><br>
            {% if article.author %}
            {{article.pub_day}} | Publicado por <strong>{{article.author.name}}</strong>
            {% else %}
            {{article.pub_day}}
            {% endif %}
            </p></li>
        {% endfor %}
    </ul>
{% endfor %}

news_scraper/templates/news/newspapers_index.html
<h1>Índice de diarios</h1>
<hr>
{% for newspaper in newspaper_list %}
    <h2><a href={% url 'news:newspaper' forloop.counter%}><strong>{{newspaper.newspaper_name}}</strong></a></h2>
{% endfor %}